-- نفّذ هذا الملف داخل Supabase SQL Editor.
-- بعد إنشاء مستخدم الإدارة من Authentication > Users،
-- ضع UUID الخاص به في INSERT الأخير.

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.links (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 80),
  url text not null check (url ~* '^https?://'),
  icon text not null default '↗' check (char_length(icon) between 1 and 8),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;
alter table public.links enable row level security;

drop policy if exists "public can read links" on public.links;
create policy "public can read links"
on public.links for select
to anon, authenticated
using (true);

drop policy if exists "admins can read admin table" on public.admins;
create policy "admins can read admin table"
on public.admins for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "admins can insert links" on public.links;
create policy "admins can insert links"
on public.links for insert
to authenticated
with check (
  exists (select 1 from public.admins a where a.user_id = auth.uid())
);

drop policy if exists "admins can update links" on public.links;
create policy "admins can update links"
on public.links for update
to authenticated
using (
  exists (select 1 from public.admins a where a.user_id = auth.uid())
)
with check (
  exists (select 1 from public.admins a where a.user_id = auth.uid())
);

drop policy if exists "admins can delete links" on public.links;
create policy "admins can delete links"
on public.links for delete
to authenticated
using (
  exists (select 1 from public.admins a where a.user_id = auth.uid())
);

-- مثال رابط أولي:
insert into public.links (title, url, icon, sort_order)
values ('تلجرام', 'https://t.me/', '✈', 1)
on conflict do nothing;

-- بعد إنشاء حسابك في Supabase، نفّذ:
-- insert into public.admins (user_id) values ('ضع-UUID-حسابك-هنا');
